# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d4b151944329153b969de5106b93baf90898caaa47dcb85db8aa35b92185ccfe288e9732d4292f87f1974ca1d2daf826795c566e4d8d7f6dbd6d1be002a55a

test:
  secret_key_base: 291b2722ceb5e51bb5335f78cf2a8a597952fd82b5cfc108f38c347ce38ea6105b64beb8a6bde47e335772b1df455d06222be8d4957768e68dd1d3f1b264c2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
